name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.0.0
        registry-url: https://registry.npmjs.com/
    - name: Install dependencies
      run: |
        npm install -g yarn
        yarn install --frozen-lockfile
    - name: Build
      run: npx lerna run build
    - name: Test
      run: npx lerna run test
